DROP TABLE IF EXISTS tweets;

CREATE TABLE tweets (id INTEGER PRIMARY KEY, timestamp TEXT, content TEXT, isTrump INTEGER, correct INTEGER, incorrect INTEGER);
INSERT INTO tweets VALUES(0,'4:46 PM - 30 Nov 2017','If you don''t like Christmas, do us all a favor and buy a one-way ticket to Syria or North Korea, where Christmas is banned',0,0,0);
INSERT INTO tweets VALUES(1,'8:13 PM - 1 Dec 2017','I don''t fear the DPRK (North Korea), I fear the local cops.',0,0,0);
INSERT INTO tweets VALUES(2,'8:20 PM - 1 Dec 2017','I know my enemy. They wear a blue uniform and a shiny badge.',0,0,0);
INSERT INTO tweets VALUES(3,'7:19 AM - 2 Dec 2017','My next tweet would have just been a bunch of profanity about the GOP and their pseudo-tax bill, so I think I''d better stop now.',0,0,0);
INSERT INTO tweets VALUES(4,'2:37 PM - 26 Nov 2017','What are some good vapes to buy that arent too expensive $30-$60',0,0,0);
INSERT INTO tweets VALUES(5,'9:43 PM - 1 Dec 2017','Kids stay away from drugs, they are bad for you.',0,0,0);
INSERT INTO tweets VALUES(6,'5:30 AM - 2 Dec 2017',replace('Hard to believe America’s business tax rate was ever 35% to begin with\n\nHuge corporations like high taxes because it eliminates competition & they just park everything offshore\n\nThis will be a huge boost to the middle class and medium sized companies who actually employ Americans','\n',char(10)),0,0,0);
INSERT INTO tweets VALUES(7,'12:48 PM - 4 Feb 2015','You won''t believe what my investigators in Canada and Cuba are finding out about Ted Cruz.',0,0,0);
INSERT INTO tweets VALUES(8,'6:10 AM - 23 Feb 2015','The #Oscars are a sad joke. Unfortunately we can''t blame Obama #Oscars2015 #OscarsSoWhite',0,0,0);
INSERT INTO tweets VALUES(9,'7:36 AM - 5 Jun 2015','Had a chance to speak to a group of five-year-olds today. Told them Obama was the worst President in their lifetime',0,0,0);
INSERT INTO tweets VALUES(10,'7:54 PM - 7 Aug 2015','I have agreed to one more Fox News debate on one condition: I get to fire one of the moderators at the end of the show #GOPDebate',0,0,0);
INSERT INTO tweets VALUES(11,'9:06 AM - 25 Oct 2015','Jeb Bush and Trey Gowdy have one thing in common: They''re both really good at wasting money #Trump2016',0,0,0);
INSERT INTO tweets VALUES(12,'12:38 PM - 1 Apr 2015','Obama’s offer to Iran will not stop Iran’s breakout capability. It is a bad, desperate deal negotiated from weakness. Pass sanctions!',1,0,0);
INSERT INTO tweets VALUES(13,'13:59 PM - Oct 28, 2012','While @BetteMidler is an extremely unattractive woman, I refuse to say that because I always insist on being politically correct.',1,0,0);
INSERT INTO tweets VALUES(14,'2:08 AM - Apr 7, 2015','How much money is the extremely unattractive (both inside and out) Arianna Huffington paying her poor ex-hubby for the use of his name?',1,0,0);
INSERT INTO tweets VALUES(15,'9:03 PM - Mar 17, 2014','There are many editorial writers that are good, some great, & some bad. But the least talented of all is frumpy Gail Collins of NYTimes.',1,0,0);
INSERT INTO tweets VALUES(16,'5:38 PM - Oct 13, 2012','They found Jessica in Colorado--- body was mutilated--- death to the pervert killer.',1,0,0);
INSERT INTO tweets VALUES(17,'3:47 PM - Apr 21, 2013','NO MERCY TO TERRORISTS you dumb bastards!',1,0,0);
INSERT INTO tweets VALUES(18,'11:35 PM - Dec 8, 2014','Our country and our "leaders" are getting dumber all the time. Now they are about to release full documentation on torture. Will destroy CIA',1,0,0);
INSERT INTO tweets VALUES(19,'3:09 PM - Aug 21, 2013','The hatchet job in @NYMag about Roger Ailes is total bullshit. He is the ultimate winner who is surrounded by a great team. @FoxNews',1,0,0);
INSERT INTO tweets VALUES(20,'12:21 AM - Sep 29, 2014','Every time I speak of the haters and losers I do so with great love and affection. They cannot help the fact that they were born fucked up!',1,0,0);
INSERT INTO tweets VALUES(21,'12:05 AM - Apr 20, 2013','Should be public execution for all to see-you will end this bullshit fast!',1,0,0);
INSERT INTO tweets VALUES(22,'3:34 PM - Apr 21, 2013','Bullshit-Pop gave me knowledge and a relatively small amount of money (split between brothers and sisters) and I built it into over 9 bill.',1,0,0);
INSERT INTO tweets VALUES(23,'6:24 PM - Jun 29, 2012','Justice Kennedy should be proud of himself for sticking to his principles, in light of Justice Roberts'' bullshit!',1,0,0);
INSERT INTO tweets VALUES(24,'1:15 AM - Nov 22, 2013','If you are lucky enough to catch a knockout assaulter before getting slugged, and you carry a gun, shoot the bastard (teach them a lesson)!',1,0,0);
INSERT INTO tweets VALUES(25,'12:39 AM - Jan 2, 2014','This very expensive GLOBAL WARMING bullshit has got to stop. Our planet is freezing, record low temps,and our GW scientists are stuck in ice',1,0,0);
INSERT INTO tweets VALUES(26,'6:44 AM - Jan 29, 2014','Give me clean, beautiful and healthy air - not the same old climate change (global warming) bullshit! I am tired of hearing this nonsense.',1,0,0);
INSERT INTO tweets VALUES(27,'3:23 AM - Mar 3, 2014','I don''t know how much longer I can take this bullshit - so terrible! #Oscars',1,0,0);
INSERT INTO tweets VALUES(28,'1:29 PM - May 25, 2013','Come on @DannyZuker, take the bet, show your friends and family (& your bosses on Modern Family) that you''re not chicken shit',1,0,0);
INSERT INTO tweets VALUES(29,'12:03 AM - May 25, 2013','@dannyzuker I hope you pick up a lot of twitter followers by this so people can see what a total asshole you are!',1,0,0);
INSERT INTO tweets VALUES(30,'6:40 PM - Apr 5, 2014','Major League Baseball was really smart when they wouldn''t let Mark Cuban buy a team. Was it his financials or the fact that he''s an asshole?',1,0,0);
INSERT INTO tweets VALUES(31,'9:47 PM - Mar 19, 2013','@mcuban Mark, okay with me but don''t start your bullshit again!',1,0,0);
INSERT INTO tweets VALUES(32,'7:36 PM - Oct 29, 2014','Obama admin. called @netanyahu "chickenshit." Ironic since Bibi was an IDF Special Forces commando while Obama was a community organizer.',1,0,0);
INSERT INTO tweets VALUES(33,'3:47 PM - Apr 21, 2013','NO MERCY TO TERRORISTS you dumb bastards!',1,0,0);
INSERT INTO tweets VALUES(34,'4:06 PM - Nov 19, 2012','It makes me feel so good to hit "sleazebags" back -- much better than seeing a psychiatrist (which I never have!)',1,0,0);
INSERT INTO tweets VALUES(35,'2:50 PM - Jun 27, 2015','When somebody challenges you unfairly, fight back - be brutal, be tough - don''t take it. It is always important to WIN!',1,0,0);
INSERT INTO tweets VALUES(36,'3:42 AM - Apr 7, 2015','Many journalists are honest and great - but some are knowingly dishonest and basic scum. They should.be weeded out!',1,0,0);
INSERT INTO tweets VALUES(37,'2:10 AM - Sep 27, 2014','The animal who beheaded the woman in Oklahoma should be given a very fast trial and then the death penalty. The same fate - beheading?',1,0,0);
INSERT INTO tweets VALUES(38,'7:23 AM - Dec 12, 2014','The terrorists cut off the heads of Americans and laugh, then want to sell us the bodies for $1,000,000. We fight over sleep deprivation!',1,0,0);
INSERT INTO tweets VALUES(39,'8:36 PM - Oct 31, 2013','So we can spy on our ally’s leaders but can’t water board terrorists?',1,0,0);
INSERT INTO tweets VALUES(40,'9:27 PM - Nov 15, 2011','Waterboarding KSM gave us the intelligence that lead to Bin Laden.',1,0,0);
INSERT INTO tweets VALUES(41,'12:16 AM - Jul 13, 2013','I went to Trump Scotland last week and a gopher sexually assaulted my wife. After you, bet she loved it!',1,0,0);
INSERT INTO tweets VALUES(42,'9:44 AM - Jul 16, 2015','"Donald Trump is one of the sexiest men on this planet. Every woman dreams of a good man who tells it like it is." So true!',1,0,0);
INSERT INTO tweets VALUES(43,'3:19 PM - Mar 26, 2016','The media is so after me on women Wow, this is a tough business. Nobody has more respect for women than Donald Trump!',1,0,0);
INSERT INTO tweets VALUES(44,'7:52 PM - Apr 21, 2015','@JonahNRO You stated that I started “relentlessly tweeting like a 14-year-old girl...” Horrible insult to women. Resign now or later!',1,0,0);
INSERT INTO tweets VALUES(45,'5:28 PM - Sep 17, 2016','Wacky @NYTimesDowd, who hardly knows me, makes up things that I never said for her boring interviews and column. A neurotic dope!',1,0,0);
INSERT INTO tweets VALUES(46,'10:33 PM - Jul 24, 2016','The highly neurotic Debbie Wasserman Schultz is angry that, after stealing and cheating her way to a Crooked Hillary victory, she''s out!',1,0,0);
INSERT INTO tweets VALUES(47,'1:05 PM - Jun 3, 2016','I don''t watch or do @Morning_Joe anymore. Small audience, low ratings! I hear Mika has gone wild with hate. Joe is Joe. They lost their way!',1,0,0);
INSERT INTO tweets VALUES(48,'11:21 AM - Aug 22, 2016','Tried watching low-rated @Morning_Joe this morning, unwatchable! @morningmika is off the wall, a neurotic and not very bright mess!',1,0,0);
INSERT INTO tweets VALUES(49,'11:29 AM - Aug 22, 2016','Some day, when things calm down, I''ll tell the real story of @JoeNBC and his very insecure long-time girlfriend, @morningmika. Two clowns!',1,0,0);
INSERT INTO tweets VALUES(50,'2:50 PM - Aug 26, 2016','Wonderful @pastormarkburns was attacked viciously and unfairly on @MSNBC by crazy @morningmika on low ratings @Morning_Joe. Apologize!',1,0,0);
INSERT INTO tweets VALUES(51,'12:28 PM - Sep 2, 2016','Just heard that crazy and very dumb @morningmika had a mental breakdown while talking about me on the low ratings @Morning_Joe. Joe a mess!',1,0,0);
INSERT INTO tweets VALUES(52,'12:46 PM - Aug 8, 2015','Re Megyn Kelly quote: "you could see there was blood coming out of her eyes, blood coming out of her wherever" (NOSE). Just got on w/thought',1,0,0);
INSERT INTO tweets VALUES(53,'4:48 AM - Dec 10, 2015','.@Megynkelly spent a big part of her show talking about other shows spending so much time on me. Really weird, she''s being driven crazy!',1,0,0);
INSERT INTO tweets VALUES(54,'3:40 PM - Dec 15, 2015','I wonder if @megynkelly and her flunkies have written their scripts yet about my debate performance tonight. No matter how well I do - bad!',1,0,0);
INSERT INTO tweets VALUES(55,'3:34 PM - Dec 15, 2015','@megynkelly is very bad at math. She was totally unable to figure out the difference between me and Cruz in the new Monmouth Poll 41to14.',1,0,0);
INSERT INTO tweets VALUES(56,'8:20 PM - Jan 11, 2016','@megynkelly recently said that she can’t be wooed by Trump. She is so average in every way, who the hell wants to woo her!',1,0,0);
INSERT INTO tweets VALUES(57,'11:44 AM - Jan 27, 2016','I refuse to call Megyn Kelly a bimbo, because that would not be politically correct. Instead I will only call her a lightweight reporter!',1,0,0);
INSERT INTO tweets VALUES(58,'7:06 PM - Aug 9, 2015 ','I just realized that if you listen to Carly Fiorina for more than ten minutes straight, you develop a massive headache. She has zero chance!',1,0,0);
INSERT INTO tweets VALUES(59,'9:03 PM - Mar 17, 2014','There are many editorial writers that are good, some great, & some bad. But the least talented of all is frumpy Gail Collins of NYTimes.',1,0,0);
INSERT INTO tweets VALUES(60,'2:08 AM - Apr 7, 2015','How much money is the extremely unattractive (both inside and out) Arianna Huffington paying her poor ex-hubby for the use of his name?',1,0,0);
INSERT INTO tweets VALUES(61,'4:21 PM - May 18, 2012','Seems hard to believe that @Facebook could be worth that much--be careful if you invest. And Mark Zuckerberg--get a pre-nup.',1,0,0);
INSERT INTO tweets VALUES(62,'9:36 PM - Feb 26, 2013','@tedcruz must be doing something right if @cher, sadly rated “the 4th ugliest celebrity” according to @listverse, is attacking him.',1,0,0);
INSERT INTO tweets VALUES(63,'11:57 PM - Apr 20, 2014','Huffington Post is just upset that I said its purchase by AOL has been a disaster and that Arianna Huffington is ugly both inside and out!',1,0,0);
INSERT INTO tweets VALUES(64,'8:23 PM - Nov 13, 2012','I don’t wear a “rug”—it’s mine. And I promise not to talk about your massive plastic surgeries that didn’t work.',1,0,0);
INSERT INTO tweets VALUES(65,'8:05 PM - Oct 26, 2012','Sarah Jessica Parker voted “unsexiest woman alive” – I agree. She said “it’s beneath me to comment on the... ',1,0,0);
INSERT INTO tweets VALUES(66,'3:59 PM - Oct 28, 2012','While @BetteMidler is an extremely unattractive woman, I refuse to say that because I always insist on being politically correct.',1,0,0);
INSERT INTO tweets VALUES(67,'3:17 PM - Jun 8, 2014','The Miss U.S.A. pageant will be amazing tonight. To be politically incorrect, the girls (women) are REALLY BEAUTIFUL.',1,0,0);
INSERT INTO tweets VALUES(68,'2:13 PM - May 14, 2012','The TIME Magazine cover showing late age breast feeding is disgusting--sad what TIME did to get noticed. @TIME',1,0,0);
INSERT INTO tweets VALUES(69,'10:08 AM - Oct 1, 2014','The woman who is the Secret Service Director looks like she is way over her head.Why can''t the president appoint the best and the brightest?',1,0,0);
INSERT INTO tweets VALUES(70,'10:36 AM - May 17, 2013','Unfortunately with some men when the poison kicks in (not me of course) there are no rules or guidelines in the military that will stop them',1,0,0);
INSERT INTO tweets VALUES(71,'9:30 AM - Sep 30, 2016','Did Crooked Hillary help disgusting (check out sex tape and past) Alicia M become a U.S. citizen so she could use her in the debate?',1,0,0);
INSERT INTO tweets VALUES(72,'8:40 PM - Jan 25, 2013','Maybe I’m old fashioned but I don’t like seeing women in combat.',1,0,0);
INSERT INTO tweets VALUES(73,'11:04 PM - May 7, 2013','26,000 unreported sexual assults in the military-only 238 convictions. What did these geniuses expect when they put men & women together?',1,0,0);
INSERT INTO tweets VALUES(74,'10:06 AM - Sep 6, 2014','Attention all hackers: You are hacking everything else so please hack Obama''s college records (destroyed?) and check place of birth',1,0,0);
INSERT INTO tweets VALUES(75,'1:59 PM - Nov 1, 2012','It''s 10 AM: Two hours to go for Obama to easily pick up millions for charity!',1,0,0);
INSERT INTO tweets VALUES(76,'9:11 AM - Mar 29, 2014','I am against shooting massive doses into tiny children. Spread shots out over time.',1,0,0);
INSERT INTO tweets VALUES(77,'1:29 PM - Sep 3, 2014','No more massive injections. Tiny children are not horses—one vaccine at a time, over time.',1,0,0);
INSERT INTO tweets VALUES(78,'9:12 PM - Apr 9, 2012','Now they say obese women may cause Autism in children- nonsense, they use any excuse. ',1,0,0);
INSERT INTO tweets VALUES(79,'4:10 PM - Oct 22, 2012','Lots of autism and vaccine response. Stop these massive doses immediately. Go back to single, spread out shots! What do we have to lose.',1,0,0);
INSERT INTO tweets VALUES(80,'11:28 AM - Aug 20, 2014','Our politically correct country will read the ISIS terrorists who beheaded the reporter their Miranda Rights prior to good food & care!',1,0,0);
INSERT INTO tweets VALUES(81,'1:19 PM - Jul 20, 2012','At least 12 dead and 50 wounded in Colorado--bring back fast trials & death penalty for mass murderers & terrorists',1,0,0);
INSERT INTO tweets VALUES(82,'9:38 PM - Feb 19, 2016','Boycott all Apple products until such time as Apple gives cellphone info to authorities regarding radical Islamic terrorist couple from Cal',1,0,0);
INSERT INTO tweets VALUES(83,'1:26 AM - Jun 26, 2013','"And you''re okay with the government spying on you?" Must have power to stop terrorists etc.',1,0,0);
INSERT INTO tweets VALUES(84,'11:35 PM - Dec 8, 2014','Our country and our "leaders" are getting dumber all the time. Now they are about to release full documentation on torture. Will destroy CIA',1,0,0);
INSERT INTO tweets VALUES(85,'3:17 AM - Jan 3, 2015','I just saw the movie "Unbroken" -- very good except I thought the ending was weak, no retribution! And we complain about waterboarding.',1,0,0);
INSERT INTO tweets VALUES(86,'7:44 AM - Dec 12, 2014','Isn''t it interesting that immediately after September 11th, everybody was asking for, and indeed demanding, torture of any kind. No reports!',1,0,0);
INSERT INTO tweets VALUES(87,'7:41 PM - Jun 27, 2013','Call it any way you like, but Snowden is a traitor. When our country was great do you know what we did to traitors?',1,0,0);
INSERT INTO tweets VALUES(88,'1:59 PM - 6 Dec 2012','@Lord_Sugar I easily could but as long as Sugar is making me money (it''s my show) I won''t--unlike Sugar, I''m not stupid!',1,0,0);
INSERT INTO tweets VALUES(89,'12:56 PM - 6 Dec 2012','@Lord_Sugar  If you think ugly windmills are good for Scotland you are an even worse businessman than I thought...',1,0,0);
INSERT INTO tweets VALUES(90,'2:42 PM - 6 Dec 2012','Sugar @Lord_Sugar—you should say thank you, Donald, like a good little boy...',1,0,0);
INSERT INTO tweets VALUES(91,'5:53 PM - 8 Dec 2014','Sorry, she''s a mentally sick woman, a bully, a dummy and, above all, a loser. Other than that she is just wonderful! ',1,0,0);
INSERT INTO tweets VALUES(92,'8:10 AM - 10 May 2012','@Cher attacked @MittRomney. She is an average talent who is out of touch with reality. Like @Rosie O''Donnell, a total loser!',1,0,0);
INSERT INTO tweets VALUES(93,'5:02 PM - 29 Nov 2017','@Theresa_May, don’t focus on me, focus on the destructive Radical Islamic Terrorism that is taking place within the United Kingdom. We are doing just fine!',1,0,0);
INSERT INTO tweets VALUES(94,'8:36 PM - Oct 31, 2013','He also supposedly called Iran and said that they should not make a deal with Bush because Obama will give them a better deal.That was treason because that''s what he did!',0,0,0);
INSERT INTO tweets VALUES(95,'2:10 AM - Sep 27, 2014','How come the #Syrian pilot that was burned alive by #ISIS didn’t as much attention as the Jordanian pilot?',0,0,0);
INSERT INTO tweets VALUES(96,'4:10 AM - Sep 22, 2017','Both Russia & North Korea have proved they will use any means feasible to disrupt international affairs. #NorthKorea ',0,0,0);
INSERT INTO tweets VALUES(97,'6:40 PM - Apr 5, 2014','But anyone with a brain knows North Korea is in fact the aggressor',0,0,0);
INSERT INTO tweets VALUES(98,'3:34 PM - Apr 21, 2013','Forget the nonsense about "A rising tide lifting all boats." The truth is that far too many boats aren''t seaworthy and they will eventually sink or become mired down while captains of industry and politics enjoy smooth sailing afforded by #TaxReform.  #TaxScamBill',0,0,0);
INSERT INTO tweets VALUES(99,'9:51 AM - 29 Aug 2017','Nice and dry in Corpus Christi. Amazing storm. Record setting. Great ratings.',0,0,0);
INSERT INTO tweets VALUES(100,'9:56 AM - 7 Jun 2017','Dinner tonight at White House with Tom Cotton and Marco Rubio. Both to interview Comey tomorrow.',0,0,0);
INSERT INTO tweets VALUES(101,'6:19 AM - 1 Jun 2017','Paris Agreement is a hoax. Who needs clean air? Who needs 3 million clean-energy jobs?',0,0,0);
INSERT INTO tweets VALUES(102,'8:37 AM - 20 May 2017','Why do the Saudis keep offering me a head cover and mumbling something about "unsightly hair." #MAGA',0,0,0);
INSERT INTO tweets VALUES(103,'4:12 PM - 6 May 2017','I am shocked that Kellyanne Conway didn''t win The Kentucky Derby. The race was rigged.',0,0,0);
INSERT INTO tweets VALUES(104,'8:56 AM - 28 Apr 2017','Being President is hard. I golf every weekend to relax. Golfing was wrong for Obama, but not for me. I am working so hard. This is tough.',0,0,0);
INSERT INTO tweets VALUES(105,'1:42 PM - 2 Apr 2017','Russia investigation. No wall. No repeal and replace. No Iran deal. Golfing every weekend. Yup, I''m Making America Great Again. Circa 1928.',0,0,0);
INSERT INTO tweets VALUES(106,'8:21 AM - 28 Feb 2017','Contrary to popular belief, Kellyanne is allowed on the furniture.',0,0,0);
INSERT INTO tweets VALUES(107,'5:39 PM - 5 Feb 2017','Lady Gaga was amazing. A true patriot. Born this way. All inclusive. #LGBT #GAGA',0,0,0);
INSERT INTO tweets VALUES(108,'7:03 AM - 2 Dec 2017','Bill Clinton got one thing right: “it’s the economy stupid.” The story of the year is the booming Trump economy, which will soar to new heights if we seize this moment to cut taxes & create better jobs, higher wages, and greater prosperity for all.',0,0,0);
INSERT INTO tweets VALUES(109,'6:02 PM - 30 Nov 2017',replace('1) Enter country illegally\n2) Fire a stolen Sig Sauer handgun into a group of people\n3) Sever the aorta of a young woman & kill her\n4) Throw gun in SF Bay\n5) Get caught on video fleeing scene\n6) Watch a SF jury acquit you of the serious charges in a mockery of justice\n#Steinle','\n',char(10)),0,0,0);
INSERT INTO tweets VALUES(110,'7:52 PM - 1 Dec 2017','Looking forward to Democrats passing single payer in ten minutes at two in the morning on post it notes in @SenGillibrand’s handwriting.',0,0,0);
INSERT INTO tweets VALUES(111,'8:03 AM - 2 Dec 2017','Excuse me, CNN, it’s not “Democrats say the tax bill will add $1 trillion to the deficit.” It’s CBO and the Joint Committee on Taxation. This is a hugely important story, take the time to get it right.',0,0,0);
INSERT INTO tweets VALUES(112,'10:41 AM - 2 Dec 2015','Obviously, Democrats think illegal aliens have more rights & deserve more benefits than American citizens. A vote for a DemoRat is ignorant',0,0,0);
INSERT INTO tweets VALUES(113,'11:40 AM - 2 Dec 2017','If you hate this tax cut so much, why don’t you just keep paying the higher Obama rate?',0,0,0);
INSERT INTO tweets VALUES(114,'11:40 AM - 2 Dec 2017','Hussein Obama should''ve never lasted 1 second!!!! Total Failure',0,0,0);
INSERT INTO tweets VALUES(115,'11:39 AM - 2 Dec 2017','Did you notice Obama doubling the debt?  The Democrats won''t agree to one spending cut.',0,0,0);
INSERT INTO tweets VALUES(116,'11:39 AM - 2 Dec 2017','Did you say the same when Obama basically threatened to financially hurt you if you voted in favor of #Brexit?',0,0,0);
INSERT INTO tweets VALUES(117,'10:41 AM - 2 Dec 2015','Just curious. When Obama was ignoring the constitution. Was your voice as loud as it is now',0,0,0);
INSERT INTO tweets VALUES(118,'10:41 AM - 2 Dec 2015','President Obama isn''t leading. How is it that there are thousands of children in America.',0,0,0);

